# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Installing dependencies
      working-directory: "./backend/productService"
      run: go mod download

    - name: Building healthchecker
      working-directory: "./backend/productService"
      run: |
        go build -o healthcheck ./cmd/healthcheck
        chmod +x ./healthcheck
        ls -la healthcheck

    - name: Starting server
      working-directory: "./backend/productService/"
      run: |
        go build -o server ./cmd/server
        ./server &
        echo "SERVER_PID=$!" >> $GITHUB_ENV
        sleep 5

    - name: Waiting for server to be healthy
      working-directory: "./backend/productService"
      run: |
        echo "Running a healthchecker:"
        if ./healthcheck; then
          echo "Server is healthy"
        else
          echo "Server seems to be very ill"
          exit 1
        fi

    - name: Running server tests
      working-directory: "./backend/productService/"
      run: go test -v ./internal/...

    - name: Stopping server
      if: always()
      run: |
          if [ ! -z "$SERVER_PID" ]; then
            kill $SERVER_PID 2>/dev/null || true
          fi
